
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fluxcrossplane
  region: eu-central-1
  version: "1.22"

managedNodeGroups:
  - name: spot-ng-1
    instanceTypes: [ "t2.medium", "t3.medium" ]
    desiredCapacity: 1
    volumeSize: 20
    spot: true

