apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: eks-cluster-composition
  annotations:
    provider: aws
spec:
  crossplane:
    version: ">=v1.0.0"
  dependsOn:
    - provider: registry.upbound.io/crossplane/provider-aws
      version: ">=v0.23.0"