---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: applications-project
  source:
    path: charts/argocd-workload-app
    repoURL: <-- your GIT repository
    targetRevision: HEAD
    helm:
      values: |
        spec:
          destination:
            server: https://XXXXXXXXXXXXXXx.xxx.eu-west-3.eks.amazonaws.com
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true